spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sueros_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1128388522
spring.jpa.hibernate.ddl-auto=none