# 1. A la URL le agregamos "jdbc:" al inicio, y le BORRAMOS el usuario y la contraseña de adentro.
# También le quitamos el "-pooler" y lo del channel_binding para que conecte directo y más rápido.
spring.datasource.url=jdbc:postgresql://ep-crimson-art-aqfltc2u.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require

# 2. El usuario va aquí solito
spring.datasource.username=neondb_owner

# 3. Tu contraseña real y limpia, sin @ ni letras raras alrededor
spring.datasource.password=npg_I9BSqoMAaNP4

# 4. El driver oficial de Java para Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. Las instrucciones para que Hibernate cree las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true